### ISSUE TITLE
How can I change or define the MSSTabBarView height  with storyboard?

### ISSUE THREAD

**Issue by NSStudent** [MerrickSapsford/MSSTabbedPageViewController#11]
Hi

First thank for share this awesome controller.

I read your code and I have a question. 
How can I change or define the `MSSTabBarView` height ?, Your code has the `_height` private attribute but then you only read the `MSSTabBarViewDefaultHeight` constant.

Thanks in advance and Please excuse my limited English.

**Comment by MerrickSapsford** [comment]
Hi,

Thanks for the PR, I've added the same functionality and the ability to adjust the tab bar bottom padding in the navigation bar as well. Both are IBInspectable.

Available in [Version 0.2.2](https://github.com/MerrickSapsford/MSSTabbedPageViewController/tree/0.2.2).

Hope it's useful!

**Comment by NSStudent** [comment]
Thanks for this functionality 🎉
