### ISSUE TITLE
Couldn't able to install it via CocoaPods.

### ISSUE THREAD

**Issue by kidsid49** [MerrickSapsford/MSSTabbedPageViewController#18]
When I tried it to install via CocoaPods. I got this error.

[!] Unable to find a specification for `MSSTabbedPageViewController`

**Comment by MerrickSapsford** [comment]
Hi,

Can't quite think why this would happen, can you try cleaning the Cocoapods master repo on your machine ([http://stackoverflow.com/a/18224765](http://stackoverflow.com/a/18224765)) and ensure you are actually using the master repo in Cocoapods?

**Comment by Kleemann** [comment]
Make sure you have the platform target set to: `platform :ios, '8.0'` - not lower

**Comment by kidsid49** [comment]
@MerrickSapsford  cool it worked. Thanks :-)

**Comment by ZvOlCuOk2009** [comment]
@MerrickSapsford unbelievable! It also helped me to solve the problem:)
