### ISSUE TITLE
Code version, how to implement?

### ISSUE THREAD

**Issue by hujin95** [MerrickSapsford/MSSTabbedPageViewController#25]
Code version, how to implement?

**Comment by MerrickSapsford** [comment]
Simply initialise your `MSSTabbedPageViewController` view controller subclass in code and in the `viewControllersForPageViewController:` dataSource method, initialise all your child view controllers like you usually would in code.

**Comment by hujin95** [comment]
I have already done so, but still can't, whether navigationBar reason?

**Comment by hujin95** [comment]
他似乎没有进入,    if ([self.navigationController.navigationBar isMemberOfClass:[MSSTabNavigationBar class]] && !self.tabBarView)

**Comment by hujin95** [comment]
He doesn't seem to have entered, the if ([self. NavigationController. NavigationBar isMemberOfClass: [MSSTabNavigationBar class]] &&! Self. TabBarView)

**Comment by hujin95** [comment]
Hello, like: MSSTabbedPageViewController, could help to solve it for me?

**Comment by MerrickSapsford** [comment]
To get the tabbed navigation bar, you need to have a custom `UINavigationController` that overrides `initWithNavigationBarClass:toolbarClass`, using `[MSSTabNavigationBar class]` as the navigation bar class parameter. The navigation controller will then need the `MSSTabbedPageViewController ` view controller as its `rootViewController`.

**Comment by hujin95** [comment]
Thank you, have achieved, but the pods as if can't use?

**Comment by MerrickSapsford** [comment]
Sorry I don't quite understand what you mean?

**Comment by hujin95** [comment]
The pods are unavailable

**Comment by MerrickSapsford** [comment]
Make sure that the target in your podfile is iOS 8.0 or above. Also ensure you're using the master pods repo.

**Comment by MobileMon** [comment]
So to simplify, when instantiating the nav bar do this: navBar = UINavigationController(navigationBarClass: MSSTabNavigationBar.self, toolbarClass: nil)
