### ISSUE TITLE
userScrollEnabled isn't working

### ISSUE THREAD

**Issue by juangarciacds** [MerrickSapsford/MSSTabbedPageViewController#30]
I'm trying to disable the scroll view setting the userScrollEnabled = NO but it's not working on  Xcode 7.3.1 using Objective-C

**Comment by MerrickSapsford** [comment]
Hi,

Are you sure that the `MSSTabBarView` exists at the time you are trying to set `userScrollEnabled`? Using the `MSSTabNavigationBar`, the tab bar doesn't attach until `viewWillAppear`

**Comment by juangarciacds** [comment]
Sure, I'm setting the userScrollEnabled in the viewDidLoad method and I checked and it is not nil the instance of MSSTabBarView.
Note that I am not using a MSSTabNavigationBar I am using a UIView attached with the outlet MSSTabBarView.

**Comment by MerrickSapsford** [comment]
Okay, I can't seem to reproduce it.

Just to confirm, setting `userScrollEnabled` on the tab bar only stops the user scrolling the tab bar contents if the number of tabs extends off screen. To toggle scroll on the page view controller, there is a `scrollEnabled` property on `MSSPageViewController`

**Comment by juangarciacds** [comment]
Ok, that is the thing that I tried to do. Thanks for answer quickly
