### ISSUE TITLE
How can I change Selected Tab Font Size and Color ?

### ISSUE THREAD

**Issue by preetikat240486** [MerrickSapsford/MSSTabbedPageViewController#32]
I am facing issue while changing selected Tab Font Size "30" and on same time others tabs should have font size "10". Also when any specific tab will be selected then i want to change background color of tab. Can you please guide me how can i do that.

![thumb_img_1577_1024](https://cloud.githubusercontent.com/assets/19325173/15212782/630b0cca-1860-11e6-9028-abe8d5c6add2.jpg)

Thank you so much in advance.

**Comment by MerrickSapsford** [comment]
Hi,

I haven't added in these features just yet, will be looking at adding in better appearance customisation very shortly.

Cheers

**Comment by MerrickSapsford** [comment]
This is now available via `tabAttributes` and `selectedTabAttributes` in `MSSTabBarView` as of [0.2.7](https://github.com/MerrickSapsford/MSSTabbedPageViewController/releases/tag/0.2.7)
