### ISSUE TITLE
Feature Request: Scroll tabs

### ISSUE THREAD

**Issue by MobileMon** [MerrickSapsford/MSSTabbedPageViewController#33]
This is pretty incredible, the one thing its lacking is the ability to scroll the tabs left and right

And I mean only scroll the tabs, not then content underneath it

Can be seen in google play store

Any plans to add this feature?

**Comment by MobileMon** [comment]
if anyone wants this feature just go into MSSTabBarView.m and change to this:

`- (void)baseInit {
    
    // General
    _tabPadding = MSSTabBarViewDefaultTabPadding;
    CGFloat horizontalInset = MSSTabBarViewDefaultHorizontalContentInset;
    _contentInset = UIEdgeInsetsMake(0.0f, horizontalInset, 0.0f, horizontalInset);
    _userScrollEnabled = TRUE;`

**Comment by MerrickSapsford** [comment]
This is available via the `userScrollEnabled` property on `MSSTabBarView`

**Comment by MobileMon** [comment]
@merricksapadmi its actually buggy. it stops marking which tab is selected and gets messed up

To reproduce create a long enough list of tabs where some will be off the screen

Now keep the first tab selected

scroll the tab bar all the way to the end (just by the bar not by the pages)

then swipe a page (not the bar)

now scroll back to the first tab by tab bar (not by page)

see how visually the indicator is off

Let me know if the reproduction issues make sense
