### ISSUE TITLE
Change selected tab font

### ISSUE THREAD

**Issue by Shiju86** [MerrickSapsford/MSSTabbedPageViewController#34]
How could i change the text font size of selected tab?

**Comment by MerrickSapsford** [comment]
Now available with `selectedTabAttributes` in [0.2.7](https://github.com/MerrickSapsford/MSSTabbedPageViewController/releases/tag/0.2.7)

**Comment by Shiju86** [comment]
ohh 👍  thanks for your time. But i already did it my end.
