### ISSUE TITLE
How do I implement MSSTabbedPageViewController without UINavigationController?

### ISSUE THREAD

**Issue by hman190** [MerrickSapsford/MSSTabbedPageViewController#36]
Dear author,
I have tried what you have said in your README.md. I have attached 
> a MSSTabBarView via the tabBarView property on MSSTabbedPageViewController, and setting the dataSource and delegate of the MSSTabBarView to the view controller. 

However, the method 
` -(void)tabBarView:populateTab:atIndex:;`

is still not called. Would you please help me? What I have done is the following code:

`- (void)viewDidLoad {`
`[super viewDidLoad];`
`MSSTabBarView *tabberView = [MSSTabBarView new];`
`tabberView.delegate = self;`
`tabberView.dataSource = self;`
` [self.tabBarView addSubview:tabberView];`
`}`

Thank you so much and have a nice day!

**Comment by MerrickSapsford** [comment]
Hi,

Please see the attached [TabCodeExample.zip](https://github.com/MerrickSapsford/MSSTabbedPageViewController/files/267851/TabCodeExample.zip) project for how to add a tab bar programatically. Basically, you needed to set `self.tabBarView` to your `tabberView` and add the `tabberView` as a subview of the view controller. You can also achieve this in interface builder as all the required properties are `IBOutlet`s.

I will add an example to the demo project which shows how to add the tab bar programmatically. 

Thanks,
Merrick

**Comment by MerrickSapsford** [comment]
Example project now added in [0.2.7](https://github.com/MerrickSapsford/MSSTabbedPageViewController/releases/tag/0.2.7)

**Comment by hman190** [comment]
Thank you so much!
