### ISSUE TITLE
Swipe randomly

### ISSUE THREAD

**Issue by ignivashiju** [MerrickSapsford/MSSTabbedPageViewController#41]

**Comment by Shiju86** [comment]
When i swipe unconditionally or move child_controller using finger(swipe). Top tabs misbehave like: no tabs are selected and no bottom indicator will display.

**Comment by MerrickSapsford** [comment]
Is this happening sporadically or are the tabs not responding to interaction at all?

**Comment by Shiju86** [comment]
All the tabs not responding when i swipe immediately.

**Comment by Shiju86** [comment]
Hello Merrick

  Thanks for resolving this issue. If you don't mind, could you please tell
me where you have to change the code. So, I can check myself and understand
the code.

Regards
Shiju Varghese

**Comment by MerrickSapsford** [comment]
Hi Shiju, 

I couldn't reproduce/fully understand the issue, so wasn't able to provide a fix. If you can give me some concrete reproduction steps, or a project exhibiting the issue I'll take another look.

Cheers, 
Merrick

**Comment by Shiju86** [comment]
Ok. Do one thing. Integrate API in every page(In ChildController). Add
CollectionView or TableView, whatever you want to add in
ChildViewController. Hit API in every controller with different data. and
swipe the child controller with speedy. Then top tab behave changes, no
indicator display and no selected tab display at that moment. But this
happens only when you swipe the page unconditionally.

Regards
Shiju Varghese

On Tue, Jun 14, 2016 at 10:40 PM, Merrick Sapsford <notifications@github.com

**Comment by MerrickSapsford** [comment]
Hi,

Would you be able to provide a demo project that displays this issue?

Thanks, 
Merrick

**Comment by Shiju86** [comment]
Ok i'll provide you same.

Regards
Shiju Varghese

On Wed, Jun 15, 2016 at 12:43 AM, Merrick Sapsford <notifications@github.com
