### ISSUE TITLE
How to replace the title view of navigation controller with tab view?

### ISSUE THREAD

**Issue by internal** [MerrickSapsford/MSSTabbedPageViewController#43]
I wrote self.navigationItem.titleView = self.tabBarView; won't work.

**Comment by MerrickSapsford** [comment]
Hi,

Please see the attached demo project for using `MSSTabBarView` as a `UINavigationItem.titleView`.

[TitleView.zip](https://github.com/MerrickSapsford/MSSTabbedPageViewController/files/289476/TitleView.zip)

**Comment by internal** [comment]
Thanks. Work like a charm👍
