### ISSUE TITLE
Color not correct when use tabAttributes 

### ISSUE THREAD

**Issue by hengchengfei** [MerrickSapsford/MSSTabbedPageViewController#51]
I set color as blackColor when not selected.

but its alpha changed likely.
![3 pic_hd](https://cloud.githubusercontent.com/assets/3182964/15766047/9259ab94-296d-11e6-8abf-6dcc963aa01b.jpg)

**Comment by MerrickSapsford** [comment]
Hi,

This is now available as of #52, and will be in the 0.3.0 release. To disable the alpha effect, add `MSSTabTransitionAlphaEffectEnabled : @(NO)` to the `tabAttributes` of the tab bar.
