### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by DennisRitchieUA** [MerrickSapsford/MSSTabbedPageViewController#57]
I have a problem when minimized application, I return it NavigationBar size increases.
![2016-06-07 12 25 43](https://cloud.githubusercontent.com/assets/11030840/15852776/28d3aa44-2cab-11e6-8494-ae9035d3b3b9.png)
![simulator screen shot 7 2016 12 27 35](https://cloud.githubusercontent.com/assets/11030840/15852809/396cc994-2cab-11e6-982b-046dae611265.png)
![simulator screen shot 7 2016 12 27 43](https://cloud.githubusercontent.com/assets/11030840/15852835/4c8ab978-2cab-11e6-97a0-bc0016f120d4.png)

**Comment by DennisRitchieUA** [comment]
[newsApp 2.zip](https://github.com/MerrickSapsford/MSSTabbedPageViewController/files/306058/newsApp.2.zip)

**Comment by DennisRitchieUA** [comment]
Hi, i fix it in class MSSCustomHeightNavigationBar in method sizeThatFits
`- (CGSize)sizeThatFits:(CGSize)size {
    CGSize originalSize = [super sizeThatFits:size];
    if ([[UIApplication sharedApplication] applicationState] == UIApplicationStateActive)
        originalSize.height += [self getHeightIncreaseValue];
    
    return originalSize;
}`

**Comment by MerrickSapsford** [comment]
Hi,

Glad you've got it sorted temporarily. I'm going to have a look at figuring why it keeps trying to expand and recalculate its size incorrectly. Hopefully have a more permanent fix in the next release.

**Comment by DennisRitchieUA** [comment]
I have one more bug in version 0.3.2 . One page not have name, page in end of the collectionview, if I going begin of the collection view and go to end again, this time name showing

**Comment by mixdesign** [comment]
> I have one more bug in version 0.3.2 . One page not have name, page in end of the collectionview, if I going begin of the collection view and go to end again, this time name shown. I rolled to 0.3.0 version, in this version i not have this bug.

I have same issue.

**Comment by MerrickSapsford** [comment]
These bugs are now resolved as of version 0.3.3
