### ISSUE TITLE
Allow to change programmatically value for MSSTabBarViewDefaultTabUnselectedAlpha

### ISSUE THREAD

**Issue by pcecchetti** [MerrickSapsford/MSSTabbedPageViewController#58]
Hello

MSSTabBarViewDefaultTabUnselectedAlpha is hardcoded atm. It would be useful to define a runtime value as it is possible for many other properties.

Thank you

**Comment by MerrickSapsford** [comment]
Hi,

I'll get this added in ASAP.

Cheers

**Comment by MerrickSapsford** [comment]
This is now available as of #59. `tabAttributes` in `MSSTabBarView` now supports the key `MSSTabTitleAlpha` with a float value. This will be available in the 0.3.1 release.

Thanks

**Comment by pcecchetti** [comment]
thank you. So fast :-)

Cheers
