### ISSUE TITLE
Can I custom Tab cell?

### ISSUE THREAD

**Issue by tentenlee100** [MerrickSapsford/MSSTabbedPageViewController#6]
Can I custom Tab cell?
not only text ever backgrand color and add image

thanks.

**Comment by MerrickSapsford** [comment]
Hi,

I'm looking at adding better customisation to the tab cells in the next version.

**Comment by MerrickSapsford** [comment]
Additional appearance customisation is now available in `MSSTabBarView` in [Version 0.2.1](https://github.com/MerrickSapsford/MSSTabbedPageViewController/tree/0.2.1)
