### ISSUE TITLE
Tabbar not showing

### ISSUE THREAD

**Issue by marceloquinta** [MerrickSapsford/MSSTabbedPageViewController#60]
I followed your steps from READ-ME, but the method "(void)tabBarView:(MSSTabBarView *)tabBarView populateTab:(MSSTabBarCollectionViewCell *)tab atIndex" is not being called. Do you have some idea what should I do?

Gist from my UIViewController:
https://gist.github.com/marceloquinta/1714e7962a0bf90a891291529ff9aa48

**Comment by MerrickSapsford** [comment]
Hi,

Can you check whether `self.tabBarView` exists at `viewWillAppear:`? 

Thanks

**Comment by marceloquinta** [comment]
Yes, it was.

I solve it putting a tabBarView inside the UIView in the Storyboard and linking in with a IBOutlet. =)

**Comment by MerrickSapsford** [comment]
Glad you got it sorted.

`tabAttributes` is available in `MSSTabBarView` as of v0.2.7. Ensure you've got your master spec repo up to date (CocoaPods doesn't automatically do this on `pod install` anymore). 

Try `pod repo update`, and then `pod update` on your Podfile to get the latest version.
