### ISSUE TITLE
"MSSTabTitleAlpha" const removed?

### ISSUE THREAD

**Issue by mpd518** [MerrickSapsford/MSSTabbedPageViewController#63]
Hello,

It seems there used to be an "MSSTabTitleAlpha" const in MSSTabBarAppearance.m but I could no longer find it. Is it still supported by tabAttributes?

Thanks.

**Comment by MerrickSapsford** [comment]
Hi,

`MSSTabTitleAlpha` is not yet available in a release, so if you're using CocoaPods it isn't in v0.3.0. I will be adding v0.3.1 shortly.

Cheers,
Merrick

**Comment by MerrickSapsford** [comment]
0.3.1 is now available via CocoaPods.

Cheers
