### ISSUE TITLE
Can i reuse my tableView Inside "contentViewForPage:(ZWSPage *)page atIndex:(NSInteger)index"?

### ISSUE THREAD

**Issue by Vishaliphone** [MerrickSapsford/MSSTabbedPageViewController#66]
Hi,
I want to use reload data inside :
**- (UIView *)contentViewForPage:(ZWSPage *)page atIndex:(NSInteger)index**

I do not want to create new View Object inside this.
I want to reuse my view.
But when i do this inside **MSSTabbedPageViewController** it shows blank screen.
Please suggest any solution for this.

**Comment by MerrickSapsford** [comment]
Hi,

`MSSTabbedPageViewController` does not currently support view controller reuse. I'm not sure whether `ZWSlideViewController` does?

**Comment by MerrickSapsford** [comment]
Please continue discussion in #7
