### ISSUE TITLE
Scrolling tabbar request.

### ISSUE THREAD

**Issue by sedwo** [MerrickSapsford/MSSTabbedPageViewController#68]
This is a request for a slight enhancement to the tabbar.

As you swipe through the VC's the tabbar automatically scrolls.  But I cannot gesture scroll the tabbar itself to get me to an index quicker.  Hence, I am forced to swipe through all the VC's to get to a far index instead.

Otherwise, very nice control.

**Comment by MerrickSapsford** [comment]
Hi, 

This functionality should be available with the `scrollEnabled` property on `MSSTabBarView`. Let me know how you get on.

Cheers,
Merrick

**Comment by sedwo** [comment]
That worked!  :)
