### ISSUE TITLE
Perpetual Gesture Pan breaks tabbar index

### ISSUE THREAD

**Issue by sedwo** [MerrickSapsford/MSSTabbedPageViewController#69]
If you do a long gesture pan across views, the tabbar on top fails to keep up properly.

![scrollingbreakstabbarindex](https://cloud.githubusercontent.com/assets/1434449/16474159/37875772-3e42-11e6-882c-0afb193ca33b.gif)

**Comment by MerrickSapsford** [comment]
Hi,

Thanks for this, I'll get looking at sorting it ASAP.

**Comment by MerrickSapsford** [comment]
Resolved as of 0.3.3
