### ISSUE TITLE
tabBarView's title can not be displayed  properly in Swift Example

### ISSUE THREAD

**Issue by sunwrt** [MerrickSapsford/MSSTabbedPageViewController#72]
hi, MerrickSapsford,
I downloaded and tried your the Example. Objective-C version worked great, but Swift version can not work finely.

Following your ReadME, I had run the Example, result as follow: (Xcode 7.3.1)
Can you help me ? Thanks in advance !
![Uploading mss.jpg…]()
 
![Uploading mss-pic-2016-0710.jpg…]()

**Comment by sunwrt** [comment]
Can not upload the pic

**Comment by MerrickSapsford** [comment]
Fixed as of 0.3.3

**Comment by sunwrt** [comment]
It works, thanks
