### ISSUE TITLE
Navigation Bar Rendering Bug

### ISSUE THREAD

**Issue by akacaptain** [MerrickSapsford/MSSTabbedPageViewController#73]
We are using your component in our live app ZEN (http://bit.ly/getzenapp) and I've discovered a major flaw that made it into our production code for about a week.  I'm quite surprised that no one else has encountered this, as we can reproduce it 100% of the time.  I implemented a work-around in our app but still wanted to bring this to your attention, as the work-around is not ideal.  

The problem occurs in an MSSTabbedPageViewController subclass that is utilizing a tabBarView automatically rendered in a MSSTabNavigationBar subclass.  Here are the steps to reproduce:

- Push a view controller onto the navigation stack.  The new view controller does not display the tabBarView and is not an MSSTabbedPageViewController subclass. 

- Put the app in the background (this was the most common type of manifestation we saw of this bug, but anything that would cause the newly presented view controller to disappear will trigger it).

- Return to the app and note the black space where the navigation bar should be (see attached screenshot).  This is a result of the navigation bar being redrawn in your code, which isn't even necessary since there's no tabBarView being displayed, and the height of the navigation bar being miscalculated as if the tabBarView *is* being displayed.  Thus the navigation bar is pushed upward and is now unusable.

I was able to pinpoint where in your code this bug is occurring, but was not able to create a suitable fix due to time pressures.  As I mentioned, this bug made it into production and needed to be fixed absolutely ASAP.  The work around was to present a new UINavigationController from the current view controller, and not simply push a new view controller onto the navigation stack as I was doing before.  Again, this works but is a less than optimal solution.

Please advise.

![img_5356](https://cloud.githubusercontent.com/assets/3859922/16754442/925de580-47a7-11e6-81cc-5b8aed184b65.PNG)

**Comment by MerrickSapsford** [comment]
Hi,

Thanks for this, someone else reported something similar. Going to try and have a look at it today and get it sorted ASAP. 

Cheers,
Merrick

**Comment by MerrickSapsford** [comment]
This should be resolved in 0.3.3 :)
