### ISSUE TITLE
When swipe fast, the indication of the tab is wrong

### ISSUE THREAD

**Issue by ANNotunzdY** [MerrickSapsford/MSSTabbedPageViewController#79]
http://annotunzdy.info/github/mss.mov

**Comment by internalG** [comment]
It seems it's fixed on branch develop? Or should I wait for the v2?

**Comment by MerrickSapsford** [comment]
Hi,

I've done a bit of work recently on the page view controller scroll behaviour, so as of 0.3.8 any scroll update issues should be rectified.

Cheers
