### ISSUE TITLE
How can i use it without Storyboard ?

### ISSUE THREAD

**Issue by louk** [MerrickSapsford/MSSTabbedPageViewController#8]

**Comment by MerrickSapsford** [comment]
Simply subclass the view controller you want to use as the page view controller as a `MSSTabbedPageViewController` and in `viewControllersForPageViewController` return an array of initialized UIViewControllers.

To use the custom tab bar UINavigationBar you can utilise `initWithNavigationBarClass:toolbarClass:` in UINavigationController that has the `MSSTabbedPageViewController` view controller as its root view controller, and pass in `[MSSTabNavigationBar class]` as the navigation bar class.
