### ISSUE TITLE
Tab Disappear when use more than one StoryBoards

### ISSUE THREAD

**Issue by Sfresneda** [MerrickSapsford/MSSTabbedPageViewController#80]
When I declare my VCArray:
`
let viewControllers = [storyboard1.instantiateViewControllerWithIdentifier("view1"),
                               storyboard2.instantiateViewControllerWithIdentifier("view2")]
`
The push is correctly, but when i go back to main tabView, the tab is hidden and I can't recover it.

**Comment by MerrickSapsford** [comment]
Hi,

I can't seem to reproduce this, is there any chance you can send over a project which demo's the problem?

Cheers,
Merrick

**Comment by Sfresneda** [comment]
Ok, my problem has been solved, my problem are allocated here:
` // MARK: MSSTabBarViewDataSource
    override func tabBarView(tabBarView: MSSTabBarView, populateTab tab: MSSTabBarCollectionViewCell, atIndex index: Int) {
        
        self.tabBarView = tabBarView
.
.
.
}
`
And tabBar never be nil, and MSSTabBar not repositioned it.
I fixed it changing this line to:
`        self.tabBar = tabBarView
`

Thank so much
