### ISSUE TITLE
No TabBar View

### ISSUE THREAD

**Issue by GuessEver** [MerrickSapsford/MSSTabbedPageViewController#82]
The tabbar isn't shown
And according to the log, the function `(void)tabBarView:(MSSTabBarView *)tabBarView populateTab:(MSSTabBarCollectionViewCell *)tab atIndex:` isn't called either

MainViewController.h
```
#import <UIKit/UIKit.h>
#import "MSSTabbedPageViewController.h"

@interface MainViewController : MSSTabbedPageViewController

@end
```
MainViewController.m
![image](https://cloud.githubusercontent.com/assets/9291770/17612833/32bb0cde-6089-11e6-935c-5dc31173ff1b.png)

in AppDelegate
![image](https://cloud.githubusercontent.com/assets/9291770/17612865/95cad1b0-6089-11e6-8602-a6cea5d635c9.png)

**Comment by burakozturk16** [comment]
To manually attach a tab bar view to the MSSTabbedPageViewController:

Set the tabBarView property of the MSSTabbedPageViewController to an MSSTabBarView instance (Note: tabBarView is weak and an IBOutlet).
Set the dataSource and delegate properties of the MSSTabBarView instance to the MSSTabbedPageViewController (Both are IBOutletable).
